# This playbook can be used to enable passwordless sudo for the current user

- name: Enable passwordless sudo
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: ansible_sudo_pass
      prompt: Sudo password
      private: yes
  become: yes
  tasks:
   - name: Register whether passwordless sudoers file exists
     raw: test -e /etc/sudoers.d/passwordless-sudo
     register: passwordless_sudo_test_result
     ignore_errors: yes
     changed_when: false

   - name: Create passwordless sudoers file if it doesn't exist
     file:
       path: /etc/sudoers.d/passwordless-sudo
       state: touch
       mode: u=r,g=r,o-rwx
     when: passwordless_sudo_test_result.rc

   - name: Ensure sudo is passwordless
     lineinfile:
       dest: /etc/sudoers.d/passwordless-sudo
       regexp: ^%sudo
       line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'

