# This playbook can be used to enable passwordless sudo for the current user

- name: Enable passwordless sudo
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: ansible_sudo_pass
      prompt: Sudo password
      private: yes
  tasks:
    - name: Ensure sudo is passwordless and valid
      lineinfile:
        path: /etc/sudoers.d/passwordless-sudo
        regexp: ^%sudo
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        owner: root
        group: root
        mode: '0440'
        create: yes
        validate: 'visudo -cf %s' # Ensures you don't accidentally lock yourself out of sudo
      become: yes
      vars:
        # Works around the new sudo-rs, a new memory-safe, rust-based rewrite of sudo that Ubuntu 26.04 uses by default
        ansible_become_exe: /usr/bin/sudo.ws
