# Installs dependencies for running aws commands via ansible

- name: Install python3 requirements
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  tasks:
    - name: Ensure modern dependencies exist for local cloud uploads
      ansible.builtin.apt:
        name:
          - python3-boto3
        state: present
      become: true
