# This playbook can be used to install everything required to run ec2.py

- name: Install python3 requirements
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  tasks:
    - name: Ensure boto dependencies are installed
      apt:
        name: ['virtualenv','python3-pip']
    - name: Ensure boto is installed
      pip:
        name: ['botocore', 'boto', 'boto3']

