# This playbook can be used to configure a EC2 instance which will perform backups

- name: Ensure Python2 is installed
  include: bootstrap.yml
  
- name: Configure backup machine
  hosts: mine
  remote_user: ubuntu
  tasks:
    - name: Upgrade all packages
      apt: upgrade=safe
      become: yes
    - name: Ensure ansible installation dependency exists
      apt: name=software-properties-common
      become: yes
    - name: Ensure latest ansible repository is used
      apt_repository:
        repo: ppa:ansible/ansible
      become: yes
    - name: Ensure ansible is installed
      apt: name=ansible state=latest
      become: yes
    - name: Create SSH key if none exists
      user:
        name: ubuntu
        generate_ssh_key: yes
    - name: Ensure boto dependency virtualenv is installed
      apt: name={{item}}
      become: yes
      with_items:
        - virtualenv
        - python-pip
