# This playbook can be used to configure a EC2 instance which will perform backups

- name: Configure backup machine
  hosts: mine
  remote_user: ubuntu
  tasks:
    - name: Upgrade all packages
      apt: upgrade=safe
      become: yes
    - name: Ensure ansible installation dependency exists
      apt:
        name: ['software-properties-common']
      become: yes
    - name: Ensure ansible and sshpass is installed
      apt:
        name: ['ansible', 'sshpass']
      become: yes
    - name: Create SSH key if none exists
      user:
        name: ubuntu
        generate_ssh_key: yes
    - name: Ensure boto dependency virtualenv is installed
      apt:
        name: ['virtualenv', 'python3-pip']
      become: yes
