# This playbook can be used to perform backups remotely

- name: Configure backup machine
  hosts: mine
  remote_user: ubuntu
  tasks:
    - name: Remove ansible playbook
      file:
        path: /home/ubuntu/backup-validator
        state: absent
    - name: Ensure ansible playbook exists
      git:
        repo: 'https://github.com/benbankes/backup-validator.git'
        dest: /home/ubuntu/backup-validator
        update: no
    - name: Ensure vars folder exists
      file:
        path: /home/ubuntu/backup-validator/vars
        state: directory
    - name: Copy files with variables
      copy:
        src: "{{playbook_dir}}/../vars"
        dest: /home/ubuntu/backup-validator/

